services:
  - type: web
    name: recommender-engine
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    autoDeploy: true
